# To add fields, make a new schema file in this directory
# and change the schema setting in _config.yml to its name
dataset_fields:
  - field_name: title
    label: Title
    datajson: title
  - field_name: date_issued
    label: Date Issued (YYYY-MM-DD)
    datajson: issued
  - field_name: date_modified
    label: Date Modified (YYYY-MM-DD)
    datajson: modified
  - field_name: department
    label: department
    form_template: form/department.html
    datajson: publisher.name
  - field_name: notes
    label: Description
    form_template: form/textarea.html
    datajson: description
  - field_name: license
    label: License
    form_template: form/license.html
    datajson: license
  - field_name: category
    label: Category
    form_template: form/category.html
    display_template: display/category.html
    datajson: category
  - field_name: maintainer
    label: Maintainer
    default: City of San Diego
    datajson: contactPoint.fn
  - field_name: maintainer_email
    label: Maintainer Email
    default: data@sandiego.gov
    datajson: contactPoint.hasEmail

resource_fields:
  - field_name: name
    label: Resource Name
    datajson: distribution.title
  - field_name: url
    label: URL
    datajson: distribution.downloadURL
  - field_name: format
    label: Format
    datajson: distribution.format
    form_template: form/dropdown.html
    values:
      - api
      - csv
      - json
      - geojson
      - html
      - kml
      - kmz
      - shp
      - xml
      - pdf

department_fields:
  - field_name: title
    label: Title
  - field_name: description
    label: Description
  - field_name: logo
    label: Logo

category_fields:
  - field_name: name
    label: Name
  - field_name: logo
    label: Logo
  - field_name: logo_credit
    label: Logo Credit
  - field_name: featured
    label: Featured on Homepage
    form_template: form/checkbox.html

story_fields:
  - field_name: title
    label: Title
  - field_name: content
    label: Content

page_fields:
  - field_name: title
    label: Title
  - field_name: content
    label: Content

data_story_fields:
  - field_name: title
    label: Title
  - field_name: intro
    label: Intro
    form_template: form/textarea.html
  - field_name: author
    label: Author
  - field_name: url
    label: URL
  - field_name: featured
    label: Featured on Homepage
    form_template: form/checkbox.html
  - field_name: img
    label: Image URL

